# Generated by Django 4.1.7 on 2023-03-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=100)),
                ('store_manager', models.CharField(max_length=100)),
                ('store_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('store_image', models.ImageField(blank=True, upload_to='store_images')),
                ('store_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
