# Generated by Django 4.1.7 on 2023-03-05 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('category_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('category_description', models.TextField(blank=True, max_length=1000)),
                ('category_created', models.DateTimeField(blank=True, null=True)),
                ('category_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.store')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=1000)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_image', models.ImageField(blank=True, upload_to='product_images')),
                ('product_created', models.DateTimeField(blank=True, null=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.category')),
                ('product_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.store')),
            ],
        ),
    ]
