# Generated by Django 4.1.7 on 2023-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
