# Generated by Django 4.1.7 on 2023-03-06 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_product_product_stock_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('order_void', models.BooleanField(default=False)),
                ('order_created', models.DateTimeField(blank=True, null=True)),
                ('order_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_id', models.CharField(max_length=100)),
                ('order_item_quantity', models.IntegerField()),
                ('order_item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_item_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('order_item_created', models.DateTimeField(blank=True, null=True)),
                ('order_item_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order')),
                ('order_item_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
