# Generated by Django 4.0 on 2024-10-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_product_product_image_alter_store_store_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='dashboard.order'),
        ),
    ]
